management:
  endpoints:
    web:
      exposure:
        include: "*"

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    keep-alive-timeout: 30000
    keep-alive-time: 5000

