###
# @name = Deposit Amount
POST http://localhost:8081/service/interfaces/http/accounts/BE11862594265959/deposit
Content-Type: application/json

{
  "amount": 28.43,
  "from": "Robert",
  "description": "For the drinks at the bar"
}

###
# @name = Withdraw Amount
POST http://localhost:8081/service/interfaces/http/accounts/BE11862594265959/withdraw
Content-Type: application/json

{
  "amount": 15.78,
  "to": "Myself",
  "description": "For the amazing party"
}

###
# @name = Get Account History
GET http://localhost:8081/service/interfaces/http/accounts/BE11862594265959/history
Content-Type: application/json
