###
# @name = Register Customer
#PUT http://localhost:8080/customers/95f6a678-84c3-4637-8cb6-b5db4366d166
PUT http://localhost:8081/service/interfaces/http/customers/95f6a678-84c3-4637-8cb6-b5db4366d166
Content-Type: application/json

{
  "details": {
    "firstName": "Frederic",
    "lastName": "Gendebien",
    "birthDate": "1987-03-03"
  },
  "address": {
    "street": "Chenay",
    "number": "2",
    "postalCode": "4317",
    "city": "Aineffe",
    "country": "Belgium"
  }
}

###
# @name = Register unique Customer
#PUT http://localhost:8080/customers/95f6a678-84c3-4637-8cb6-b5db4366d166
PUT http://localhost:8081/service/interfaces/http/customers/unique/95f6a678-84c3-4637-8cb6-b5db4366d166
Content-Type: application/json

{
  "details": {
    "firstName": "Frederic",
    "lastName": "Gendebien",
    "birthDate": "1987-03-03"
  },
  "address": {
    "street": "Chenay",
    "number": "2",
    "postalCode": "4317",
    "city": "Aineffe",
    "country": "Belgium"
  }
}

###
# @name = Register Another unique Customer
PUT http://localhost:8081/service/interfaces/http/customers/unique/95f6a678-84c3-4637-8cb6-b5db4366d167
Content-Type: application/json

{
  "details": {
    "firstName": "Marcel",
    "lastName": "Patoulatchy",
    "birthDate": "1967-01-02"
  },
  "address": {
    "street": "Avenue de la Paix",
    "number": "69",
    "postalCode": "5678",
    "city": "Foutisse",
    "country": "Belgium"
  }
}

###
# @name = Get Customer Dashboard
GET http://localhost:8081/service/interfaces/http/customers/95f6a678-84c3-4637-8cb6-b5db4366d166/dashboard
Content-Type: application/json

###
# @name = Get Another Customer Dashboard
GET http://localhost:8081/service/interfaces/http/customers/95f6a678-84c3-4637-8cb6-b5db4366d167/dashboard
Content-Type: application/json
